// === Carga · datos de la rutina (generado desde rutina_app.json) ===
// Torso/Pierna 4 días · hipertrofia · casa con mancuernas (hasta 10 kg) + banco.
export const DUMBBELL_CAP_KG = 10;

export const DAYS = [
  {
    id: "d1", name: "Torso A", group: "torso", durMin: 41,
    exercises: [
      { id: "d1e1", name: "Press banca con mancuernas", scheme: "3 × 8-12", sets: 3, repLow: 8, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 7, rmInicial: 9.8, video: "https://www.youtube.com/results?search_query=press+banca+con+mancuernas+tecnica+correcta",
        mainMuscle: "Pecho", secMuscles: ["Hombros", "Tríceps"], mainTokens: ["chest"], secTokens: ["shoulders", "triceps"],
        estimulo: {"chest": 1.0, "shoulders": 0.5, "triceps": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Túmbate con los pies bien apoyados y las escápulas retraídas.", "Baja las mancuernas controlando hasta la altura del pecho y empuja sin bloquear los codos de golpe.", "Codos a unos 45° respecto al torso."],
        respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
        cues: ["Ahora toca pecho: no rebotes la mancuerna abajo.", "Ahora toca pecho: codos a unos 45°, no abiertos del todo.", "Ahora toca pecho: baja con control, no dejes caer el peso."],
        ejecucion: "Túmbate con los pies bien apoyados y las escápulas retraídas. Baja las mancuernas controlando hasta la altura del pecho y empuja sin bloquear los codos de golpe. Codos a unos 45° respecto al torso.",
        error: "Cuidado con abrir los codos a 90°; mantenlos a ~45° del torso para cuidar el hombro.",
        variant:
        { name: "Flexiones (push-up)", scheme: "3 × 8-15", sets: 3, repLow: 8, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "2 min", restMin: 120, restMax: 120, tempo: "2-0-1", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=flexiones+push+up+tecnica+correcta",
          mainMuscle: "Pecho", secMuscles: ["Tríceps", "Hombros", "Abdomen"], mainTokens: ["chest"], secTokens: ["triceps", "shoulders", "abdominals"],
          estimulo: {"chest": 1.0, "triceps": 0.5, "shoulders": 0.5, "abdominals": 0.5}, durMin: 7, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Manos algo más anchas que los hombros y cuerpo en línea recta.", "Baja el pecho casi al suelo con los codos a ~45° y empuja sin hundir la cadera."],
          respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
          ejecucion: "Manos algo más anchas que los hombros y cuerpo en línea recta. Baja el pecho casi al suelo con los codos a ~45° y empuja sin hundir la cadera.",
          error: "Cuidado con abrir del todo los codos o dejar caer la cadera; mantén el cuerpo rígido en plancha.",
        },
      },
      { id: "d1e2", name: "Remo a una mano con mancuerna", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=remo+a+una+mano+con+mancuerna+tecnica",
        mainMuscle: "Espalda media", secMuscles: ["Bíceps", "Dorsales", "Hombros"], mainTokens: ["middle back"], secTokens: ["biceps", "lats", "shoulders"],
        estimulo: {"middle back": 1.0, "biceps": 0.5, "lats": 0.5, "shoulders": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Apoya rodilla y mano del mismo lado en el banco, con la espalda neutra y casi paralela al suelo.", "Tira del codo hacia la cadera llevando la mancuerna al costado; aprieta la espalda arriba y baja con control."],
        respiracion: "Exhala al tirar (acercar el peso); inhala al volver.", repBuena: "Notas la espalda apretarse arriba y el codo llega atrás, sin tirón de bíceps.",
        cues: ["Ahora toca espalda: tira con el codo, no con el bíceps.", "Ahora toca espalda: no gires el torso para subir más peso.", "Ahora toca espalda: aprieta arriba un instante, no tires por inercia."],
        ejecucion: "Apoya rodilla y mano del mismo lado en el banco, con la espalda neutra y casi paralela al suelo. Tira del codo hacia la cadera llevando la mancuerna al costado; aprieta la espalda arriba y baja con control.",
        error: "Cuidado con girar el tronco para subir más peso; mantén la espalda fija y tira con el codo.",
        variant:
        { name: "Remo con dos mancuernas inclinado", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=remo+con+mancuernas+inclinado+tecnica",
          mainMuscle: "Espalda media / Dorsales", secMuscles: ["Bíceps", "Hombros"], mainTokens: ["middle back", "lats"], secTokens: ["biceps", "shoulders"],
          estimulo: {"middle back": 1.0, "lats": 1.0, "biceps": 0.5, "shoulders": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Tronco inclinado ~45° y espalda neutra.", "Rema con ambas mancuernas llevando los codos hacia atrás y apretando la espalda; baja controlado."],
          respiracion: "Exhala al tirar (acercar el peso); inhala al volver.", repBuena: "Notas la espalda apretarse arriba y el codo llega atrás, sin tirón de bíceps.",
          ejecucion: "Tronco inclinado ~45° y espalda neutra. Rema con ambas mancuernas llevando los codos hacia atrás y apretando la espalda; baja controlado.",
          error: "Cuidado con redondear la espalda o tirar con los bíceps; lleva los codos atrás.",
        },
      },
      { id: "d1e3", name: "Press militar sentado con mancuernas", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=press+militar+sentado+mancuernas+tecnica",
        mainMuscle: "Hombros", secMuscles: ["Tríceps"], mainTokens: ["shoulders"], secTokens: ["triceps"],
        estimulo: {"shoulders": 1.0, "triceps": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Sentado con la espalda apoyada y el core firme.", "Empuja las mancuernas desde la altura de los hombros hasta arriba sin arquear la lumbar.", "Baja hasta la altura de las orejas."],
        respiracion: "Inhala y aprieta el core antes de empujar; exhala al subir.", repBuena: "Subes hasta extender sin arquear la lumbar; bajas a la altura de las orejas.",
        cues: ["Ahora toca hombro: no arquees la lumbar al empujar.", "Ahora toca hombro: baja hasta las orejas, no te quedes a medias.", "Ahora toca hombro: sube sin impulsar con las piernas."],
        ejecucion: "Sentado con la espalda apoyada y el core firme. Empuja las mancuernas desde la altura de los hombros hasta arriba sin arquear la lumbar. Baja hasta la altura de las orejas.",
        error: "Cuidado con arquear la lumbar al empujar; aprieta el core y no metas la espalda.",
        variant:
        { name: "Press Arnold", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2 min", restMin: 120, restMax: 120, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=press+arnold+mancuernas+tecnica",
          mainMuscle: "Hombros", secMuscles: ["Tríceps"], mainTokens: ["shoulders"], secTokens: ["triceps"],
          estimulo: {"shoulders": 1.0, "triceps": 0.5}, durMin: 7, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Empiezas con las palmas hacia ti a la altura del pecho; al subir rotas las muñecas hasta palmas al frente y extiendes arriba.", "Baja invirtiendo el giro."],
          respiracion: "Inhala y aprieta el core antes de empujar; exhala al subir.", repBuena: "Subes hasta extender sin arquear la lumbar; bajas a la altura de las orejas.",
          ejecucion: "Empiezas con las palmas hacia ti a la altura del pecho; al subir rotas las muñecas hasta palmas al frente y extiendes arriba. Baja invirtiendo el giro.",
          error: "Cuidado con arquear la lumbar o subir con impulso; core firme.",
        },
      },
      { id: "d1e4", name: "Aperturas en banco inclinado", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 5, rmInicial: 7.5, video: "https://www.youtube.com/results?search_query=aperturas+banco+inclinado+mancuernas",
        mainMuscle: "Pecho", secMuscles: ["Hombros"], mainTokens: ["chest"], secTokens: ["shoulders"],
        estimulo: {"chest": 1.0, "shoulders": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["Tumbado en banco inclinado con los codos ligeramente flexionados y fijos.", "Abre los brazos en arco hasta notar estiramiento en el pecho y cierra como si abrazaras un barril.", "No exageres la bajada."],
        respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
        cues: ["Ahora toca pecho: es una apertura, no un press; codos fijos.", "Ahora toca pecho: no bajes tanto que fuerces el hombro.", "Ahora toca pecho: busca el estiramiento, no el peso máximo."],
        ejecucion: "Tumbado en banco inclinado con los codos ligeramente flexionados y fijos. Abre los brazos en arco hasta notar estiramiento en el pecho y cierra como si abrazaras un barril. No exageres la bajada.",
        error: "Cuidado con bajar de más o flexionar mucho el codo; arco amplio con codos casi fijos.",
        variant:
        { name: "Aperturas planas con mancuernas", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 5, rmInicial: 7.5, video: "https://www.youtube.com/results?search_query=aperturas+con+mancuernas+banco+plano",
          mainMuscle: "Pecho", secMuscles: ["Hombros"], mainTokens: ["chest"], secTokens: ["shoulders"],
          estimulo: {"chest": 1.0, "shoulders": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["Tumbado en banco plano, codos algo flexionados y fijos.", "Abre en arco hasta notar estiramiento del pecho y cierra como si abrazaras un barril."],
          respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
          ejecucion: "Tumbado en banco plano, codos algo flexionados y fijos. Abre en arco hasta notar estiramiento del pecho y cierra como si abrazaras un barril.",
          error: "Cuidado con bajar de más o doblar mucho el codo.",
        },
      },
      { id: "d1e5", name: "Curl de bíceps", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 6, rmInicial: 9.0, video: "https://www.youtube.com/results?search_query=curl+de+biceps+con+mancuernas+tecnica",
        mainMuscle: "Bíceps", secMuscles: ["Antebrazos"], mainTokens: ["biceps"], secTokens: ["forearms"],
        estimulo: {"biceps": 1.0, "forearms": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["De pie, codos pegados al torso.", "Sube las mancuernas contrayendo el bíceps sin balancear el cuerpo.", "Baja lento controlando toda la fase."],
        respiracion: "Exhala al subir el peso; inhala al bajar.", repBuena: "El bíceps se contrae arriba sin balanceo y bajas controlando.",
        cues: ["Ahora toca bíceps: sin balanceo, que no tire la espalda.", "Ahora toca bíceps: codos quietos pegados al cuerpo.", "Ahora toca bíceps: baja lento, no dejes caer la mancuerna."],
        ejecucion: "De pie, codos pegados al torso. Sube las mancuernas contrayendo el bíceps sin balancear el cuerpo. Baja lento controlando toda la fase.",
        error: "Cuidado con balancear el cuerpo para impulsar; codos pegados y solo mueve el antebrazo.",
        variant:
        { name: "Curl concentrado", scheme: "2 × 12-15 (lado)", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 6, rmInicial: 9.0, video: "https://www.youtube.com/results?search_query=curl+concentrado+mancuerna+tecnica",
          mainMuscle: "Bíceps", secMuscles: ["Antebrazos"], mainTokens: ["biceps"], secTokens: ["forearms"],
          estimulo: {"biceps": 1.0, "forearms": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["Sentado, con el codo apoyado en la cara interna del muslo.", "Sube la mancuerna contrayendo el bíceps y baja lento sin balanceo."],
          respiracion: "Exhala al subir el peso; inhala al bajar.", repBuena: "El bíceps se contrae arriba sin balanceo y bajas controlando.",
          ejecucion: "Sentado, con el codo apoyado en la cara interna del muslo. Sube la mancuerna contrayendo el bíceps y baja lento sin balanceo.",
          error: "Cuidado con despegar el codo del muslo o usar impulso.",
        },
      },
      { id: "d1e6", name: "Extensión de tríceps sobre la cabeza", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 6, rmInicial: 9.0, video: "https://www.youtube.com/results?search_query=extension+triceps+sobre+la+cabeza+mancuerna",
        mainMuscle: "Tríceps", secMuscles: [], mainTokens: ["triceps"], secTokens: [],
        estimulo: {"triceps": 1.0}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["Sujeta una mancuerna con ambas manos por encima de la cabeza.", "Baja flexionando solo los codos (mantenlos apuntando arriba) y extiende sin bloquear bruscamente."],
        respiracion: "Exhala al extender el codo; inhala al flexionar.", repBuena: "Extiendes el codo del todo con el hombro quieto.",
        cues: ["Ahora toca tríceps: no abras los codos hacia los lados.", "Ahora toca tríceps: codos quietos apuntando arriba.", "Ahora toca tríceps: controla detrás de la nuca, sin tirones."],
        ejecucion: "Sujeta una mancuerna con ambas manos por encima de la cabeza. Baja flexionando solo los codos (mantenlos apuntando arriba) y extiende sin bloquear bruscamente.",
        error: "Cuidado con abrir los codos hacia los lados; mantenlos apuntando arriba y quietos.",
        variant:
        { name: "Patada de tríceps con mancuerna", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 5, rmInicial: 7.5, video: "https://www.youtube.com/results?search_query=patada+de+triceps+con+mancuerna+tecnica",
          mainMuscle: "Tríceps", secMuscles: [], mainTokens: ["triceps"], secTokens: [],
          estimulo: {"triceps": 1.0}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["Tronco inclinado, brazo pegado al costado y codo arriba.", "Extiende el antebrazo hacia atrás hasta estirar el tríceps; baja controlado."],
          respiracion: "Exhala al extender el codo; inhala al flexionar.", repBuena: "Extiendes el codo del todo con el hombro quieto.",
          ejecucion: "Tronco inclinado, brazo pegado al costado y codo arriba. Extiende el antebrazo hacia atrás hasta estirar el tríceps; baja controlado.",
          error: "Cuidado con mover el hombro o balancear; solo se mueve el antebrazo.",
        },
      },
    ],
  },
  {
    id: "d2", name: "Pierna A", group: "pierna", durMin: 46,
    exercises: [
      { id: "d2e1", name: "Sentadilla goblet", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 8, rmInicial: 12.0, video: "https://www.youtube.com/results?search_query=sentadilla+goblet+tecnica+correcta",
        mainMuscle: "Cuádriceps", secMuscles: ["Gemelos", "Glúteos", "Isquios", "Lumbar"], mainTokens: ["quadriceps"], secTokens: ["calves", "glutes", "hamstrings", "lower back"],
        estimulo: {"quadriceps": 1.0, "calves": 0.5, "glutes": 0.5, "hamstrings": 0.5, "lower back": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Mancuerna pegada al pecho, pies a la anchura de los hombros.", "Baja sacando la cadera atrás y abriendo las rodillas, espalda recta, hasta que los muslos queden al menos paralelos.", "Sube empujando con los talones."],
        respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
        cues: ["Ahora toca cuádriceps: no metas las rodillas hacia dentro.", "Ahora toca cuádriceps: baja al menos hasta paralelo, no te quedes corto.", "Ahora toca cuádriceps: talones en el suelo, no de puntillas."],
        ejecucion: "Mancuerna pegada al pecho, pies a la anchura de los hombros. Baja sacando la cadera atrás y abriendo las rodillas, espalda recta, hasta que los muslos queden al menos paralelos. Sube empujando con los talones.",
        error: "Cuidado con dejar caer las rodillas hacia dentro; empújalas hacia fuera y talones en el suelo.",
        variant:
        { name: "Sentadilla con 2 mancuernas", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 8, rmInicial: 12.0, video: "https://www.youtube.com/results?search_query=sentadilla+con+mancuernas+tecnica",
          mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["glutes", "hamstrings"],
          estimulo: {"quadriceps": 1.0, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Una mancuerna en cada mano a los lados, pies a la anchura de hombros.", "Baja sacando la cadera atrás con la espalda recta hasta muslos paralelos y sube empujando los talones."],
          respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
          ejecucion: "Una mancuerna en cada mano a los lados, pies a la anchura de hombros. Baja sacando la cadera atrás con la espalda recta hasta muslos paralelos y sube empujando los talones.",
          error: "Cuidado con que las rodillas caigan hacia dentro o redondear la espalda.",
        },
      },
      { id: "d2e2", name: "Peso muerto rumano con mancuernas", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "3-0-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=peso+muerto+rumano+mancuernas+tecnica",
        mainMuscle: "Isquios", secMuscles: ["Glúteos", "Lumbar"], mainTokens: ["hamstrings"], secTokens: ["glutes", "lower back"],
        estimulo: {"hamstrings": 1.0, "glutes": 0.5, "lower back": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Mancuernas frente a los muslos, rodillas algo flexionadas y fijas.", "Lleva la cadera hacia atrás bajando las mancuernas pegadas a las piernas hasta notar tensión en los isquios.", "Sube empujando la cadera adelante."],
        respiracion: "Inhala al bajar la cadera; exhala al subir.", repBuena: "Sientes el estiramiento en los isquios y la espalda se mantiene recta.",
        cues: ["Ahora toca femoral: cadera atrás, no lo conviertas en sentadilla.", "Ahora toca femoral: espalda recta, no la curves al bajar.", "Ahora toca femoral: mancuernas pegadas a las piernas."],
        ejecucion: "Mancuernas frente a los muslos, rodillas algo flexionadas y fijas. Lleva la cadera hacia atrás bajando las mancuernas pegadas a las piernas hasta notar tensión en los isquios. Sube empujando la cadera adelante.",
        error: "Cuidado con redondear la espalda; columna neutra y bisagra llevando la cadera atrás.",
        variant:
        { name: "Buenos días con mancuerna", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "3-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=buenos+dias+ejercicio+mancuerna+tecnica",
          mainMuscle: "Isquios", secMuscles: ["Glúteos", "Lumbar"], mainTokens: ["hamstrings"], secTokens: ["glutes", "lower back"],
          estimulo: {"hamstrings": 1.0, "glutes": 0.5, "lower back": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Mancuerna sujeta al pecho, rodillas algo flexionadas.", "Lleva la cadera atrás bajando el tronco con la espalda recta hasta notar los isquios; sube extendiendo la cadera."],
          respiracion: "Inhala al bajar la cadera; exhala al subir.", repBuena: "Sientes el estiramiento en los isquios y la espalda se mantiene recta.",
          ejecucion: "Mancuerna sujeta al pecho, rodillas algo flexionadas. Lleva la cadera atrás bajando el tronco con la espalda recta hasta notar los isquios; sube extendiendo la cadera.",
          error: "Cuidado con redondear la lumbar o flexionar mucho las rodillas.",
        },
      },
      { id: "d2e3", name: "Zancada búlgara", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=sentadilla+bulgara+tecnica",
        mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["glutes", "hamstrings"],
        estimulo: {"quadriceps": 1.0, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Empeine del pie trasero sobre el banco.", "Baja flexionando la rodilla delantera hasta unos 90°, con el tronco ligeramente inclinado.", "Empuja con el talón delantero para subir.", "Controla el equilibrio."],
        respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
        cues: ["Ahora toca pierna: baja de verdad, no te quedes corto.", "Ahora toca pierna: peso en el talón delantero, no en la punta.", "Ahora toca pierna: tronco estable, no des bandazos para equilibrarte."],
        ejecucion: "Empeine del pie trasero sobre el banco. Baja flexionando la rodilla delantera hasta unos 90°, con el tronco ligeramente inclinado. Empuja con el talón delantero para subir. Controla el equilibrio.",
        error: "Cuidado con inclinar el tronco o que la rodilla delantera se vaya hacia dentro.",
        variant:
        { name: "Zancada inversa con mancuernas", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=zancada+inversa+con+mancuernas+tecnica",
          mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["glutes", "hamstrings"],
          estimulo: {"quadriceps": 1.0, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["De pie con mancuernas a los lados.", "Da un paso atrás y baja la rodilla trasera hacia el suelo con el tronco erguido; empuja con la pierna delantera para volver."],
          respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
          ejecucion: "De pie con mancuernas a los lados. Da un paso atrás y baja la rodilla trasera hacia el suelo con el tronco erguido; empuja con la pierna delantera para volver.",
          error: "Cuidado con que la rodilla delantera pase la punta del pie o inclinar el tronco.",
        },
      },
      { id: "d2e4", name: "Puente de glúteo con mancuerna", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-1-1", pesoInicial: 8, rmInicial: 12.0, video: "https://www.youtube.com/results?search_query=puente+de+gluteo+con+mancuerna+hip+thrust+suelo",
        mainMuscle: "Glúteos", secMuscles: ["Isquios"], mainTokens: ["glutes"], secTokens: ["hamstrings"],
        estimulo: {"glutes": 1.0, "hamstrings": 0.5}, durMin: 6, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Boca arriba, mancuerna sobre la cadera, pies apoyados cerca del glúteo.", "Eleva la cadera apretando los glúteos hasta alinear tronco y muslos.", "Pausa arriba y baja sin apoyar del todo."],
        respiracion: "Inhala al bajar la cadera; exhala al subir.", repBuena: "Sientes el estiramiento en los isquios y la espalda se mantiene recta.",
        cues: ["Ahora toca glúteo: aprieta arriba, no arquees la lumbar.", "Ahora toca glúteo: empuja con los talones, no con las puntas.", "Ahora toca glúteo: no apoyes del todo abajo, mantén tensión."],
        ejecucion: "Boca arriba, mancuerna sobre la cadera, pies apoyados cerca del glúteo. Eleva la cadera apretando los glúteos hasta alinear tronco y muslos. Pausa arriba y baja sin apoyar del todo.",
        error: "Cuidado con hiperextender la lumbar arriba; sube apretando glúteos, no la espalda.",
        variant:
        { name: "Hip thrust en banco", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-1-1", pesoInicial: 8, rmInicial: 12.0, video: "https://www.youtube.com/results?search_query=hip+thrust+con+mancuerna+banco+tecnica",
          mainMuscle: "Glúteos", secMuscles: ["Isquios"], mainTokens: ["glutes"], secTokens: ["hamstrings"],
          estimulo: {"glutes": 1.0, "hamstrings": 0.5}, durMin: 6, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Espalda alta apoyada en el banco, mancuerna sobre la cadera y pies firmes.", "Eleva la cadera apretando glúteos hasta alinear tronco y muslos; pausa arriba."],
          respiracion: "Inhala al bajar la cadera; exhala al subir.", repBuena: "Sientes el estiramiento en los isquios y la espalda se mantiene recta.",
          ejecucion: "Espalda alta apoyada en el banco, mancuerna sobre la cadera y pies firmes. Eleva la cadera apretando glúteos hasta alinear tronco y muslos; pausa arriba.",
          error: "Cuidado con hiperextender la lumbar; el empuje sale del glúteo.",
        },
      },
      { id: "d2e5", name: "Elevación de gemelo de pie", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1",
        descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-1-2", pesoInicial: 8, rmInicial: 13.3, video: "https://www.youtube.com/results?search_query=elevacion+de+gemelos+de+pie+tecnica",
        mainMuscle: "Gemelos", secMuscles: [], mainTokens: ["calves"], secTokens: [],
        estimulo: {"calves": 1.0}, durMin: 6, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["De pie (con mancuernas para más carga), eleva los talones poniéndote de puntillas al máximo.", "Pausa arriba 1 segundo y baja lento estirando el gemelo.", "En un escalón ganas rango."],
        respiracion: "Exhala al subir de puntillas; inhala al bajar.", repBuena: "Subida máxima de puntillas, pausa arriba y estiramiento completo abajo.",
        cues: ["Ahora toca gemelo: sube al máximo, no hagas medio recorrido.", "Ahora toca gemelo: pausa arriba, no rebotes.", "Ahora toca gemelo: baja lento estirando, sin caer de golpe."],
        ejecucion: "De pie (con mancuernas para más carga), eleva los talones poniéndote de puntillas al máximo. Pausa arriba 1 segundo y baja lento estirando el gemelo. En un escalón ganas rango.",
        error: "Cuidado con rebotar y usar poco rango; sube del todo y baja estirando el gemelo.",
        variant:
        { name: "Gemelo a una pierna en un escalón", scheme: "3 × 12-15 (lado)", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1",
          descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-1-2", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=elevacion+de+gemelo+a+una+pierna+escalon",
          mainMuscle: "Gemelos", secMuscles: ["Gemelos"], mainTokens: ["calves"], secTokens: ["calves"],
          estimulo: {"calves": 1.0}, durMin: 5, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["Punta del pie en el borde de un escalón, sujétate para el equilibrio.", "Sube de puntillas al máximo, pausa, y baja estirando el gemelo por debajo del nivel del escalón."],
          respiracion: "Exhala al subir de puntillas; inhala al bajar.", repBuena: "Subida máxima de puntillas, pausa arriba y estiramiento completo abajo.",
          ejecucion: "Punta del pie en el borde de un escalón, sujétate para el equilibrio. Sube de puntillas al máximo, pausa, y baja estirando el gemelo por debajo del nivel del escalón.",
          error: "Cuidado con rebotar y usar poco rango.",
        },
      },
      { id: "d2e6", name: "Plancha frontal", scheme: "3 × 30-45 seg", sets: 3, repLow: 30, repHigh: 45, unit: "seg", rir: "None",
        descanso: "1 min", restMin: 60, restMax: 60, tempo: "—", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=plancha+abdominal+tecnica+correcta",
        mainMuscle: "Abdomen", secMuscles: [], mainTokens: ["abdominals"], secTokens: [],
        estimulo: {"abdominals": 1.0}, durMin: 5, tipo: "core", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "No necesarias.",
        pasos: ["Apóyate sobre antebrazos y puntas de los pies, con el cuerpo en línea recta de la cabeza a los talones.", "Aprieta abdomen y glúteos, sin hundir ni elevar la cadera.", "Respira con normalidad."],
        respiracion: "Respira de forma controlada; no aguantes la respiración.", repBuena: "Mantienes la zona lumbar estable y el movimiento es lento y controlado.",
        cues: ["Ahora toca core: no dejes caer la cadera.", "Ahora toca core: no subas el culo buscando descanso.", "Ahora toca core: respira, no aguantes la respiración."],
        ejecucion: "Apóyate sobre antebrazos y puntas de los pies, con el cuerpo en línea recta de la cabeza a los talones. Aprieta abdomen y glúteos, sin hundir ni elevar la cadera. Respira con normalidad.",
        error: "Cuidado con hundir o elevar la cadera; cuerpo en línea recta de cabeza a talones.",
        variant:
        { name: "Dead bug", scheme: "3 × 8-10 (lado)", sets: 3, repLow: 8, repHigh: 10, unit: "reps", rir: "None",
          descanso: "1 min", restMin: 60, restMax: 60, tempo: "controlado", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=dead+bug+ejercicio+core+tecnica",
          mainMuscle: "Abdomen", secMuscles: [], mainTokens: ["abdominals"], secTokens: [],
          estimulo: {"abdominals": 1.0}, durMin: 4, tipo: "core", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "No necesarias.",
          pasos: ["Boca arriba, brazos hacia el techo y caderas/rodillas a 90°.", "Baja a la vez el brazo y la pierna contrarios sin despegar la lumbar del suelo; alterna lados."],
          respiracion: "Respira de forma controlada; no aguantes la respiración.", repBuena: "Mantienes la zona lumbar estable y el movimiento es lento y controlado.",
          ejecucion: "Boca arriba, brazos hacia el techo y caderas/rodillas a 90°. Baja a la vez el brazo y la pierna contrarios sin despegar la lumbar del suelo; alterna lados.",
          error: "Cuidado con arquear la lumbar; mantenla pegada al suelo.",
        },
      },
    ],
  },
  {
    id: "d3", name: "Torso B", group: "torso", durMin: 39,
    exercises: [
      { id: "d3e1", name: "Press inclinado con mancuernas", scheme: "3 × 8-12", sets: 3, repLow: 8, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=press+inclinado+con+mancuernas+tecnica",
        mainMuscle: "Pecho", secMuscles: ["Hombros", "Tríceps"], mainTokens: ["chest"], secTokens: ["shoulders", "triceps"],
        estimulo: {"chest": 1.0, "shoulders": 0.5, "triceps": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Banco a 30-45° y escápulas retraídas.", "Baja las mancuernas a la parte alta del pecho y empuja hacia arriba juntándolas ligeramente.", "Codos a unos 45°, sin rebotar abajo."],
        respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
        cues: ["Ahora toca pecho: no rebotes abajo ni bloquees arriba de golpe.", "Ahora toca pecho: banco a 30-45°, no demasiado vertical (eso es hombro).", "Ahora toca pecho: baja a la parte alta del pecho, controlado."],
        ejecucion: "Banco a 30-45° y escápulas retraídas. Baja las mancuernas a la parte alta del pecho y empuja hacia arriba juntándolas ligeramente. Codos a unos 45°, sin rebotar abajo.",
        error: "Cuidado con rebotar abajo o abrir los codos; baja controlado y mantén ~45°.",
        variant:
        { name: "Flexiones con pies elevados", scheme: "3 × 8-15", sets: 3, repLow: 8, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "2 min", restMin: 120, restMax: 120, tempo: "2-0-1", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=flexiones+con+pies+elevados+tecnica",
          mainMuscle: "Pecho", secMuscles: ["Hombros", "Tríceps"], mainTokens: ["chest"], secTokens: ["shoulders", "triceps"],
          estimulo: {"chest": 1.0, "shoulders": 0.5, "triceps": 0.5}, durMin: 7, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Pies sobre un banco y manos algo más anchas que los hombros.", "Baja el pecho controlando con los codos a ~45° y empuja manteniendo el cuerpo recto."],
          respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
          ejecucion: "Pies sobre un banco y manos algo más anchas que los hombros. Baja el pecho controlando con los codos a ~45° y empuja manteniendo el cuerpo recto.",
          error: "Cuidado con hundir la cadera o abrir del todo los codos.",
        },
      },
      { id: "d3e2", name: "Remo con apoyo de pecho", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 7, rmInicial: 9.8, video: "https://www.youtube.com/results?search_query=remo+con+apoyo+de+pecho+mancuernas+banco+inclinado",
        mainMuscle: "Espalda media", secMuscles: ["Bíceps", "Antebrazos", "Dorsales", "Hombros"], mainTokens: ["middle back"], secTokens: ["biceps", "forearms", "lats", "shoulders"],
        estimulo: {"middle back": 1.0, "biceps": 0.5, "forearms": 0.5, "lats": 0.5, "shoulders": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Tumbado boca abajo sobre el banco inclinado, con el pecho apoyado.", "Deja colgar los brazos y rema llevando los codos hacia atrás, apretando la espalda.", "Baja con control."],
        respiracion: "Exhala al tirar (acercar el peso); inhala al volver.", repBuena: "Notas la espalda apretarse arriba y el codo llega atrás, sin tirón de bíceps.",
        cues: ["Ahora toca espalda: pecho pegado al banco, no te despegues para hacer trampa.", "Ahora toca espalda: lleva los codos atrás, no encojas los hombros.", "Ahora toca espalda: aprieta la espalda, no tires solo con los brazos."],
        ejecucion: "Tumbado boca abajo sobre el banco inclinado, con el pecho apoyado. Deja colgar los brazos y rema llevando los codos hacia atrás, apretando la espalda. Baja con control.",
        error: "Cuidado con tirar con los bíceps en vez de la espalda; lleva los codos hacia atrás.",
        variant:
        { name: "Remo a una mano con mancuerna", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=remo+a+una+mano+mancuerna+tecnica",
          mainMuscle: "Espalda media / Dorsales", secMuscles: ["Bíceps", "Hombros"], mainTokens: ["middle back", "lats"], secTokens: ["biceps", "shoulders"],
          estimulo: {"middle back": 1.0, "lats": 1.0, "biceps": 0.5, "shoulders": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Rodilla y mano del mismo lado en el banco, espalda paralela al suelo.", "Tira del codo hacia la cadera llevando la mancuerna al costado; baja controlado."],
          respiracion: "Exhala al tirar (acercar el peso); inhala al volver.", repBuena: "Notas la espalda apretarse arriba y el codo llega atrás, sin tirón de bíceps.",
          ejecucion: "Rodilla y mano del mismo lado en el banco, espalda paralela al suelo. Tira del codo hacia la cadera llevando la mancuerna al costado; baja controlado.",
          error: "Cuidado con girar el tronco o tirar con el bíceps.",
        },
      },
      { id: "d3e3", name: "Elevaciones laterales", scheme: "3 × 12-20", sets: 3, repLow: 12, repHigh: 20, unit: "reps", rir: "1-2",
        descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-0-1", pesoInicial: 4, rmInicial: 6.7, video: "https://www.youtube.com/results?search_query=elevaciones+laterales+hombro+tecnica",
        mainMuscle: "Hombros", secMuscles: [], mainTokens: ["shoulders"], secTokens: [],
        estimulo: {"shoulders": 1.0}, durMin: 6, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["De pie, con una leve flexión de codo.", "Eleva las mancuernas hacia los lados hasta la altura de los hombros, liderando con los codos.", "Sube sin impulso y baja lento; no pases del hombro."],
        respiracion: "Exhala al subir los brazos; inhala al bajar.", repBuena: "Subes liderando con el codo hasta la altura del hombro, sin impulso.",
        cues: ["Ahora toca hombro: ni impulso ni subir por encima del hombro.", "Ahora toca hombro: lidera con los codos, no con las manos.", "Ahora toca hombro: poco peso bien hecho, no cargues de más."],
        ejecucion: "De pie, con una leve flexión de codo. Eleva las mancuernas hacia los lados hasta la altura de los hombros, liderando con los codos. Sube sin impulso y baja lento; no pases del hombro.",
        error: "Cuidado con usar impulso y pasar del hombro; sube controlado hasta la altura del hombro.",
        variant:
        { name: "Elevación lateral con banda", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1-2",
          descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-0-1", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=elevaciones+laterales+con+banda+tecnica",
          mainMuscle: "Hombros", secMuscles: [], mainTokens: ["shoulders"], secTokens: [],
          estimulo: {"shoulders": 1.0}, durMin: 6, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["De pie sobre la banda, sujeta los extremos.", "Eleva los brazos a los lados hasta la altura del hombro liderando con los codos; baja lento."],
          respiracion: "Exhala al subir los brazos; inhala al bajar.", repBuena: "Subes liderando con el codo hasta la altura del hombro, sin impulso.",
          ejecucion: "De pie sobre la banda, sujeta los extremos. Eleva los brazos a los lados hasta la altura del hombro liderando con los codos; baja lento.",
          error: "Cuidado con usar impulso o subir por encima del hombro.",
        },
      },
      { id: "d3e4", name: "Pullover con mancuerna", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-1-1", pesoInicial: 7, rmInicial: 10.5, video: "https://www.youtube.com/results?search_query=pullover+con+mancuerna+tecnica",
        mainMuscle: "Pecho", secMuscles: ["Dorsales", "Hombros", "Tríceps"], mainTokens: ["chest"], secTokens: ["lats", "shoulders", "triceps"],
        estimulo: {"chest": 1.0, "lats": 0.5, "shoulders": 0.5, "triceps": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["Tumbado en el banco, sujeta una mancuerna con ambas manos sobre el pecho.", "Llévala en arco por detrás de la cabeza con los codos casi rectos hasta notar estiramiento, y regresa contrayendo pecho y dorsal."],
        respiracion: "Inhala al llevar el peso atrás; exhala al volver.", repBuena: "Notas el estiramiento del dorsal y vuelves con control.",
        cues: ["Ahora toca espalda: codos casi fijos, no flexiones para 'ayudarte'.", "Ahora toca espalda: rango cómodo detrás, no fuerces el hombro.", "Ahora toca espalda: controla la bajada, no dejes caer el peso."],
        ejecucion: "Tumbado en el banco, sujeta una mancuerna con ambas manos sobre el pecho. Llévala en arco por detrás de la cabeza con los codos casi rectos hasta notar estiramiento, y regresa contrayendo pecho y dorsal.",
        error: "Cuidado con doblar mucho los codos o arquear la lumbar; brazos casi rectos, costillas abajo.",
        variant:
        { name: "Pullover en suelo", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-1-1", pesoInicial: 7, rmInicial: 10.5, video: "https://www.youtube.com/results?search_query=pullover+con+mancuerna+suelo+tecnica",
          mainMuscle: "Pecho / Dorsales", secMuscles: ["Tríceps"], mainTokens: ["chest", "lats"], secTokens: ["triceps"],
          estimulo: {"chest": 1.0, "lats": 1.0, "triceps": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["Tumbado en el suelo, mancuerna con ambas manos sobre el pecho.", "Llévala en arco tras la cabeza con los codos casi rectos hasta estirar, y vuelve.", "El suelo limita el rango."],
          respiracion: "Inhala al llevar el peso atrás; exhala al volver.", repBuena: "Notas el estiramiento del dorsal y vuelves con control.",
          ejecucion: "Tumbado en el suelo, mancuerna con ambas manos sobre el pecho. Llévala en arco tras la cabeza con los codos casi rectos hasta estirar, y vuelve. El suelo limita el rango.",
          error: "Cuidado con doblar mucho los codos o arquear la lumbar.",
        },
      },
      { id: "d3e5", name: "Curl martillo", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 6, rmInicial: 9.0, video: "https://www.youtube.com/results?search_query=curl+martillo+mancuernas+tecnica",
        mainMuscle: "Bíceps", secMuscles: ["Antebrazos"], mainTokens: ["biceps"], secTokens: ["forearms"],
        estimulo: {"biceps": 1.0, "forearms": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["Como el curl, pero con agarre neutro (palmas enfrentadas), pulgares hacia arriba.", "Sube sin balanceo y baja controlado.", "Trabaja el braquial y el antebrazo."],
        respiracion: "Exhala al subir el peso; inhala al bajar.", repBuena: "El bíceps se contrae arriba sin balanceo y bajas controlando.",
        cues: ["Ahora toca brazo: agarre neutro, palmas enfrentadas todo el rato.", "Ahora toca brazo: sin balanceo, codos quietos.", "Ahora toca brazo: baja controlando, no sueltes de golpe."],
        ejecucion: "Como el curl, pero con agarre neutro (palmas enfrentadas), pulgares hacia arriba. Sube sin balanceo y baja controlado. Trabaja el braquial y el antebrazo.",
        error: "Cuidado con balancear el cuerpo; agarre neutro, codos quietos y bajada controlada.",
        variant:
        { name: "Curl de bíceps alterno", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 6, rmInicial: 9.0, video: "https://www.youtube.com/results?search_query=curl+de+biceps+alterno+mancuernas+tecnica",
          mainMuscle: "Bíceps", secMuscles: ["Antebrazos"], mainTokens: ["biceps"], secTokens: ["forearms"],
          estimulo: {"biceps": 1.0, "forearms": 0.5}, durMin: 4, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["De pie, sube alternando cada mancuerna rotando la palma hacia arriba al subir; codos pegados al torso y sin balanceo."],
          respiracion: "Exhala al subir el peso; inhala al bajar.", repBuena: "El bíceps se contrae arriba sin balanceo y bajas controlando.",
          ejecucion: "De pie, sube alternando cada mancuerna rotando la palma hacia arriba al subir; codos pegados al torso y sin balanceo.",
          error: "Cuidado con balancear el cuerpo para impulsar.",
        },
      },
      { id: "d3e6", name: "Press cerrado en suelo", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: 7, rmInicial: 10.5, video: "https://www.youtube.com/results?search_query=press+cerrado+mancuernas+suelo+triceps",
        mainMuscle: "Tríceps", secMuscles: ["Pecho", "Hombros"], mainTokens: ["triceps"], secTokens: ["chest", "shoulders"],
        estimulo: {"triceps": 1.0, "chest": 0.5, "shoulders": 0.5}, durMin: 4, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Tumbado en el suelo, mancuernas con agarre neutro y codos pegados al cuerpo.", "Empuja hacia arriba enfocando el tríceps.", "El suelo limita el rango y protege los hombros."],
        respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
        cues: ["Ahora toca tríceps: codos pegados al cuerpo, no abiertos.", "Ahora toca tríceps: el suelo marca el rango, no rebotes los codos.", "Ahora toca tríceps: empuja pensando en el tríceps, no en el pecho."],
        ejecucion: "Tumbado en el suelo, mancuernas con agarre neutro y codos pegados al cuerpo. Empuja hacia arriba enfocando el tríceps. El suelo limita el rango y protege los hombros.",
        error: "Cuidado con abrir los codos; mantenlos pegados al cuerpo para enfocar el tríceps.",
        variant:
        { name: "Fondos en banco (bench dips)", scheme: "2 × 10-15", sets: 2, repLow: 10, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", restMin: 60, restMax: 120, tempo: "2-0-1", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=fondos+en+banco+triceps+tecnica",
          mainMuscle: "Tríceps", secMuscles: ["Pecho", "Hombros"], mainTokens: ["triceps"], secTokens: ["chest", "shoulders"],
          estimulo: {"triceps": 1.0, "chest": 0.5, "shoulders": 0.5}, durMin: 4, tipo: "compuesto", tipoCarga: "no_axial", prioridad: "principal", fatiga: "media", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Manos en el borde del banco y piernas al frente.", "Baja flexionando los codos pegados al cuerpo hasta ~90° y empuja con el tríceps para subir."],
          respiracion: "Inhala al bajar el peso; exhala al empujar.", repBuena: "Rango completo hasta el pecho, sin rebote y bloqueo suave arriba.",
          ejecucion: "Manos en el borde del banco y piernas al frente. Baja flexionando los codos pegados al cuerpo hasta ~90° y empuja con el tríceps para subir.",
          error: "Cuidado con abrir los codos o bajar de más (estrés en el hombro).",
        },
      },
    ],
  },
  {
    id: "d4", name: "Pierna B", group: "pierna", durMin: 48,
    exercises: [
      { id: "d4e1", name: "Zancada inversa con mancuernas", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=zancada+inversa+con+mancuernas+tecnica",
        mainMuscle: "Cuádriceps", secMuscles: ["Gemelos", "Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["calves", "glutes", "hamstrings"],
        estimulo: {"quadriceps": 1.0, "calves": 0.5, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["De pie con mancuernas a los lados.", "Da un paso atrás y baja la rodilla trasera hacia el suelo manteniendo el tronco erguido.", "Empuja con la pierna delantera para volver."],
        respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
        cues: ["Ahora toca pierna: paso atrás firme, no pierdas el equilibrio.", "Ahora toca pierna: tronco erguido, no te vayas hacia delante.", "Ahora toca pierna: baja la rodilla de atrás, no te quedes corto."],
        ejecucion: "De pie con mancuernas a los lados. Da un paso atrás y baja la rodilla trasera hacia el suelo manteniendo el tronco erguido. Empuja con la pierna delantera para volver.",
        error: "Cuidado con que la rodilla delantera pase la punta del pie; mantén el tronco erguido.",
        variant:
        { name: "Zancada hacia delante con mancuernas", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=zancada+frontal+con+mancuernas+tecnica",
          mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["glutes", "hamstrings"],
          estimulo: {"quadriceps": 1.0, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Paso al frente bajando la cadera hasta que la rodilla trasera casi toca el suelo; empuja con el talón delantero para volver."],
          respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
          ejecucion: "Paso al frente bajando la cadera hasta que la rodilla trasera casi toca el suelo; empuja con el talón delantero para volver.",
          error: "Cuidado con que la rodilla delantera pase la punta del pie.",
        },
      },
      { id: "d4e2", name: "Peso muerto rumano a una pierna", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "3-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=peso+muerto+rumano+a+una+pierna+tecnica",
        mainMuscle: "Isquios", secMuscles: ["Glúteos", "Lumbar"], mainTokens: ["hamstrings"], secTokens: ["glutes", "lower back"],
        estimulo: {"hamstrings": 1.0, "glutes": 0.5, "lower back": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Sobre una pierna, mancuerna(s) al frente.", "Lleva la cadera hacia atrás bajando el tronco mientras la pierna libre se extiende hacia atrás.", "Espalda recta y subida controlada.", "Es un buen reto de equilibrio."],
        respiracion: "Inhala al bajar la cadera; exhala al subir.", repBuena: "Sientes el estiramiento en los isquios y la espalda se mantiene recta.",
        cues: ["Ahora toca femoral: cadera atrás, no curves la espalda.", "Ahora toca femoral: ve despacio, el equilibrio es parte del ejercicio.", "Ahora toca femoral: no hagas sentadilla, es bisagra de cadera."],
        ejecucion: "Sobre una pierna, mancuerna(s) al frente. Lleva la cadera hacia atrás bajando el tronco mientras la pierna libre se extiende hacia atrás. Espalda recta y subida controlada. Es un buen reto de equilibrio.",
        error: "Cuidado con que la cadera se abra de lado; mantén las caderas niveladas y la espalda recta.",
        variant:
        { name: "PM rumano a dos piernas con mancuernas", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "3-0-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=peso+muerto+rumano+mancuernas+tecnica",
          mainMuscle: "Isquios", secMuscles: ["Glúteos", "Lumbar"], mainTokens: ["hamstrings"], secTokens: ["glutes", "lower back"],
          estimulo: {"hamstrings": 1.0, "glutes": 0.5, "lower back": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Mancuernas frente a los muslos, rodillas algo flexionadas.", "Cadera atrás bajando con la espalda recta hasta notar los isquios; sube extendiendo la cadera."],
          respiracion: "Inhala al bajar la cadera; exhala al subir.", repBuena: "Sientes el estiramiento en los isquios y la espalda se mantiene recta.",
          ejecucion: "Mancuernas frente a los muslos, rodillas algo flexionadas. Cadera atrás bajando con la espalda recta hasta notar los isquios; sube extendiendo la cadera.",
          error: "Cuidado con redondear la espalda.",
        },
      },
      { id: "d4e3", name: "Sentadilla goblet con tempo", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "3-1-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=sentadilla+goblet+tempo+lento+excentrica",
        mainMuscle: "Cuádriceps", secMuscles: ["Gemelos", "Glúteos", "Isquios", "Lumbar"], mainTokens: ["quadriceps"], secTokens: ["calves", "glutes", "hamstrings", "lower back"],
        estimulo: {"quadriceps": 1.0, "calves": 0.5, "glutes": 0.5, "hamstrings": 0.5, "lower back": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Igual que la goblet, pero baja en 3-4 segundos controlando cada centímetro y sube a velocidad normal.", "El tempo lento aumenta el estímulo con poco peso."],
        respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
        cues: ["Ahora toca cuádriceps: baja en 3-4 s, no aceleres la bajada.", "Ahora toca cuádriceps: rodillas hacia fuera, no hacia dentro.", "Ahora toca cuádriceps: el peso es lo de menos, manda el tempo."],
        ejecucion: "Igual que la goblet, pero baja en 3-4 segundos controlando cada centímetro y sube a velocidad normal. El tempo lento aumenta el estímulo con poco peso.",
        error: "Cuidado con acelerar la bajada; controla los 3-4 segundos de descenso.",
        variant:
        { name: "Sentadilla con 2 mancuernas (tempo)", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "3-1-1", pesoInicial: 8, rmInicial: 11.2, video: "https://www.youtube.com/results?search_query=sentadilla+con+mancuernas+tempo+lento",
          mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["glutes", "hamstrings"],
          estimulo: {"quadriceps": 1.0, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Una mancuerna en cada mano; baja en 3-4 segundos controlando, pausa breve abajo y sube a velocidad normal."],
          respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
          ejecucion: "Una mancuerna en cada mano; baja en 3-4 segundos controlando, pausa breve abajo y sube a velocidad normal.",
          error: "Cuidado con acelerar la bajada.",
        },
      },
      { id: "d4e4", name: "Step-up al banco", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "1-2",
        descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=step+up+al+cajon+con+mancuernas+tecnica",
        mainMuscle: "Cuádriceps", secMuscles: ["Gemelos", "Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["calves", "glutes", "hamstrings"],
        estimulo: {"quadriceps": 1.0, "calves": 0.5, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
        calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
        pasos: ["Coloca un pie completo sobre el banco.", "Sube empujando con ese talón hasta extender la pierna, sin impulsarte con la pierna de abajo.", "Baja controlado.", "Mancuernas a los lados para añadir carga."],
        respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
        cues: ["Ahora toca pierna: sube con el pie de arriba, no te impulses con el de abajo.", "Ahora toca pierna: pie completo en el banco, no de puntillas.", "Ahora toca pierna: baja controlando, no te dejes caer."],
        ejecucion: "Coloca un pie completo sobre el banco. Sube empujando con ese talón hasta extender la pierna, sin impulsarte con la pierna de abajo. Baja controlado. Mancuernas a los lados para añadir carga.",
        error: "Cuidado con impulsarte con la pierna de abajo; sube empujando solo con la pierna de arriba.",
        variant:
        { name: "Zancada búlgara", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", restMin: 120, restMax: 180, tempo: "2-0-1", pesoInicial: 6, rmInicial: 8.4, video: "https://www.youtube.com/results?search_query=sentadilla+bulgara+tecnica",
          mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "Isquios"], mainTokens: ["quadriceps"], secTokens: ["glutes", "hamstrings"],
          estimulo: {"quadriceps": 1.0, "glutes": 0.5, "hamstrings": 0.5}, durMin: 8, tipo: "compuesto", tipoCarga: "axial", prioridad: "principal", fatiga: "alta", etiquetas: [],
          calienta: true, calientaTxt: "1-2 series de aproximación al 50-60% antes de las efectivas.",
          pasos: ["Empeine del pie trasero en el banco; baja la rodilla delantera a ~90° con el tronco algo inclinado y empuja con el talón delantero."],
          respiracion: "Inhala arriba y aprieta el core; exhala al subir de la sentadilla.", repBuena: "Bajas al menos a paralelo con el talón firme y subes sin que la rodilla ceda hacia dentro.",
          ejecucion: "Empeine del pie trasero en el banco; baja la rodilla delantera a ~90° con el tronco algo inclinado y empuja con el talón delantero.",
          error: "Cuidado con inclinar demasiado el tronco o que la rodilla caiga hacia dentro.",
        },
      },
      { id: "d4e5", name: "Elevación de gemelo sentado", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1",
        descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-1-2", pesoInicial: 8, rmInicial: 13.3, video: "https://www.youtube.com/results?search_query=elevacion+de+gemelos+sentado+tecnica",
        mainMuscle: "Gemelos", secMuscles: [], mainTokens: ["calves"], secTokens: [],
        estimulo: {"calves": 1.0}, durMin: 6, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
        pasos: ["Sentado, con las mancuernas apoyadas sobre las rodillas.", "Eleva los talones poniéndote de puntillas, pausa arriba y baja lento.", "Enfatiza el sóleo."],
        respiracion: "Exhala al subir de puntillas; inhala al bajar.", repBuena: "Subida máxima de puntillas, pausa arriba y estiramiento completo abajo.",
        cues: ["Ahora toca gemelo: rango completo, no medio movimiento.", "Ahora toca gemelo: pausa arriba, sin rebotes.", "Ahora toca gemelo: baja lento estirando bien."],
        ejecucion: "Sentado, con las mancuernas apoyadas sobre las rodillas. Eleva los talones poniéndote de puntillas, pausa arriba y baja lento. Enfatiza el sóleo.",
        error: "Cuidado con poco rango y rebote; pausa arriba y estira abajo.",
        variant:
        { name: "Gemelo de pie con mancuernas", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1",
          descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-1-2", pesoInicial: 8, rmInicial: 13.3, video: "https://www.youtube.com/results?search_query=elevacion+de+gemelos+de+pie+tecnica",
          mainMuscle: "Gemelos", secMuscles: ["Gemelos"], mainTokens: ["calves"], secTokens: ["calves"],
          estimulo: {"calves": 1.0}, durMin: 6, tipo: "aislamiento", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "Opcional: 1 serie ligera para notar el músculo.",
          pasos: ["De pie con mancuernas para añadir carga, sube de puntillas al máximo, pausa arriba y baja estirando el gemelo."],
          respiracion: "Exhala al subir de puntillas; inhala al bajar.", repBuena: "Subida máxima de puntillas, pausa arriba y estiramiento completo abajo.",
          ejecucion: "De pie con mancuernas para añadir carga, sube de puntillas al máximo, pausa arriba y baja estirando el gemelo.",
          error: "Cuidado con rebotar y usar poco rango.",
        },
      },
      { id: "d4e6", name: "Elevación de piernas tumbado", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-0-2", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=elevacion+de+piernas+tumbado+abdomen+tecnica",
        mainMuscle: "Abdomen", secMuscles: [], mainTokens: ["abdominals"], secTokens: [],
        estimulo: {"abdominals": 1.0}, durMin: 5, tipo: "core", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
        calienta: false, calientaTxt: "No necesarias.",
        pasos: ["Boca arriba, manos bajo los glúteos.", "Sube las piernas casi rectas controlando, sin despegar la lumbar de golpe, y baja lento sin tocar el suelo."],
        respiracion: "Respira de forma controlada; no aguantes la respiración.", repBuena: "Mantienes la zona lumbar estable y el movimiento es lento y controlado.",
        cues: ["Ahora toca abdomen: no despegues la lumbar de golpe.", "Ahora toca abdomen: baja controlando, no dejes caer las piernas.", "Ahora toca abdomen: si tiras de cuello o cadera, reduce el rango."],
        ejecucion: "Boca arriba, manos bajo los glúteos. Sube las piernas casi rectas controlando, sin despegar la lumbar de golpe, y baja lento sin tocar el suelo.",
        error: "Cuidado con despegar la lumbar y arquear; mantén la zona baja pegada al suelo.",
        variant:
        { name: "Crunch inverso", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1 min", restMin: 60, restMax: 60, tempo: "2-0-2", pesoInicial: null, rmInicial: null, video: "https://www.youtube.com/results?search_query=crunch+inverso+ejercicio+tecnica",
          mainMuscle: "Abdomen", secMuscles: ["Flexores de cadera"], mainTokens: ["abdominals"], secTokens: ["hip flexors"],
          estimulo: {"abdominals": 1.0, "hip flexors": 0.5}, durMin: 5, tipo: "core", tipoCarga: "no_axial", prioridad: "accesorio", fatiga: "baja", etiquetas: [],
          calienta: false, calientaTxt: "No necesarias.",
          pasos: ["Boca arriba, lleva las rodillas hacia el pecho elevando la pelvis del suelo con control; baja sin arquear la lumbar."],
          respiracion: "Respira de forma controlada; no aguantes la respiración.", repBuena: "Mantienes la zona lumbar estable y el movimiento es lento y controlado.",
          ejecucion: "Boca arriba, lleva las rodillas hacia el pecho elevando la pelvis del suelo con control; baja sin arquear la lumbar.",
          error: "Cuidado con usar impulso o arquear la lumbar.",
        },
      },
    ],
  },
];

export const VOLUME_TARGET = {"shoulders": 15.0, "quadriceps": 15.0, "hamstrings": 15.0, "glutes": 13.5, "calves": 12.0, "chest": 11.0, "triceps": 9.5, "biceps": 7.0, "middle back": 6.0, "lower back": 6.0, "abdominals": 6.0, "lats": 4.0, "forearms": 3.5};

export const PRINCIPLES = [
  { title: "Frecuencia y reparto", body: "4 sesiones (p. ej. Lun · Mar · Jue · Vie), cada grupo muscular entrenado 2 veces por semana. Calienta 5 min antes de cada sesión." },
  { title: "Sobrecarga progresiva (doble progresión)", body: "Empieza en el extremo bajo del rango con buena técnica. Cuando alcances el extremo alto en todas las series, sube peso. Al llegar a tu tope de 10 kg, progresa con más repeticiones, fase excéntrica más lenta (3-4 s) o versiones a una pierna/un brazo." },
  { title: "Esfuerzo (RIR)", body: "El RIR son las repeticiones que dejas 'en la recámara'. RIR 2 = podrías hacer 2 más con buena forma. Prioriza la técnica antes que llegar al fallo." },
  { title: "Suplementación y recuperación", body: "Proteína 1,6-2,2 g por kg de peso al día. Creatina 3-5 g diarios constantes (la hora es indiferente). Dormir bien es donde se construye el músculo." },
  { title: "Tempo", body: "Velocidad de cada fase de la repetición en segundos (excéntrica-pausa-concéntrica). Ej.: 3-1-1 = bajar en 3 s, pausa de 1 s, subir en 1 s. Alargar la bajada sube el estímulo sin tocar el peso: una de tus palancas al toparte con los 10 kg." },
  { title: "Variante (↳)", body: "Bajo cada ejercicio tienes una alternativa casera con sus mismos datos, por si te falla el banco, quieres variar el estímulo o algo te molesta." },
  { title: "Nota", body: "Plan orientativo. Ajusta cargas y volumen según tu recuperación. Ante dolor (no la molestia muscular normal), detente y revisa la técnica. Los enlaces abren una búsqueda en YouTube con buenas demostraciones del ejercicio." },
];

// Medios: imagen principal y de la variante. FED en 2 fotogramas (animación); GIF externo anima solo.

export const EXERCISE_MEDIA = {
  d1e1: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Pushups/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Pushups/1.jpg"], source: "Free Exercise DB", ok: false } },
  d1e2: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/One-Arm_Dumbbell_Row/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/One-Arm_Dumbbell_Row/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent_Over_Two-Dumbbell_Row/1.jpg"], source: "Free Exercise DB", ok: false } },
  d1e3: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Shoulder_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Shoulder_Press/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Arnold_Dumbbell_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Arnold_Dumbbell_Press/1.jpg"], source: "Free Exercise DB", ok: false } },
  d1e4: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Flyes/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Flyes/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Flyes/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Flyes/1.jpg"], source: "Free Exercise DB", ok: true } },
  d1e5: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bicep_Curl/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bicep_Curl/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Concentration_Curls/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Concentration_Curls/1.jpg"], source: "Free Exercise DB", ok: false } },
  d1e6: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Dumbbell_Triceps_Extension/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Tricep_Dumbbell_Kickback/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Tricep_Dumbbell_Kickback/1.jpg"], source: "Free Exercise DB", ok: false } },
  d2e1: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/1.jpg"], source: "Free Exercise DB", ok: true } },
  d2e2: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Stiff-Legged_Dumbbell_Deadlift/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Good_Mornings/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Good_Mornings/1.jpg"], source: "Free Exercise DB", ok: false } },
  d2e3: { main: { urls: ["https://fitnessprogramer.com/wp-content/uploads/2021/05/Dumbbell-Bulgarian-Split-Squat.gif"], source: "fitnessprogramer.com", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Rear_Lunge/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Rear_Lunge/1.jpg"], source: "Free Exercise DB", ok: true } },
  d2e4: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Butt_Lift_Bridge/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Butt_Lift_Bridge/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Hip_Thrust/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Hip_Thrust/1.jpg"], source: "Free Exercise DB", ok: false } },
  d2e5: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/1.jpg"], source: "Free Exercise DB", ok: true } },
  d2e6: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: [], source: "", ok: false } },
  d3e1: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Press/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Decline_Push-Up/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Decline_Push-Up/1.jpg"], source: "Free Exercise DB", ok: false } },
  d3e2: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Incline_Row/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Incline_Row/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/One-Arm_Dumbbell_Row/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/One-Arm_Dumbbell_Row/1.jpg"], source: "Free Exercise DB", ok: true } },
  d3e3: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Side_Lateral_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Side_Lateral_Raise/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Side_Lateral_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Side_Lateral_Raise/1.jpg"], source: "Free Exercise DB", ok: false } },
  d3e4: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent-Arm_Dumbbell_Pullover/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent-Arm_Dumbbell_Pullover/1.jpg"], source: "Free Exercise DB", ok: true } },
  d3e5: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Alternate_Hammer_Curl/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Alternate_Hammer_Curl/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Alternate_Bicep_Curl/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Alternate_Bicep_Curl/1.jpg"], source: "Free Exercise DB", ok: false } },
  d3e6: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Floor_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Floor_Press/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bench_Dips/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bench_Dips/1.jpg"], source: "Free Exercise DB", ok: false } },
  d4e1: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Rear_Lunge/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Rear_Lunge/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Lunges/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Lunges/1.jpg"], source: "Free Exercise DB", ok: true } },
  d4e2: { main: { urls: ["https://fitnessprogramer.com/wp-content/uploads/2022/09/Dumbbell-Single-Leg-Deadlift.gif"], source: "fitnessprogramer.com", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Stiff-Legged_Dumbbell_Deadlift/1.jpg"], source: "Free Exercise DB", ok: false } },
  d4e3: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/1.jpg"], source: "Free Exercise DB", ok: true } },
  d4e4: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Step_Ups/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Step_Ups/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://fitnessprogramer.com/wp-content/uploads/2021/05/Dumbbell-Bulgarian-Split-Squat.gif"], source: "fitnessprogramer.com", ok: false } },
  d4e5: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Seated_One-Leg_Calf_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Seated_One-Leg_Calf_Raise/1.jpg"], source: "Free Exercise DB", ok: true }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/1.jpg"], source: "Free Exercise DB", ok: true } },
  d4e6: { main: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Flat_Bench_Lying_Leg_Raise/1.jpg"], source: "Free Exercise DB", ok: false }, variant: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Reverse_Crunch/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Reverse_Crunch/1.jpg"], source: "Free Exercise DB", ok: false } },
};

export function exerciseImages(exId, variant = false) {
  const m = EXERCISE_MEDIA[exId]; if (!m) return [];
  const slot = variant ? m.variant : m.main;
  return (slot && slot.urls) ? slot.urls : [];
}

export function exerciseSource(exId, variant = false) {
  const m = EXERCISE_MEDIA[exId]; if (!m) return "";
  const slot = variant ? m.variant : m.main;
  return (slot && slot.source) ? slot.source : "";
}

export const EXERCISE_INDEX = (() => {
  const idx = {};
  for (const day of DAYS) for (const ex of day.exercises) idx[ex.id] = { ...ex, dayId: day.id, dayName: day.name };
  return idx;
})();

export function videoUrl(name) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(name + " técnica mancuernas");
}
