// Rutina de hipertrofia · Torso/Pierna 4 días · casa con mancuernas (hasta 10 kg) y banco.
// Datos fijos extraídos de tu Excel. La app solo guarda tu seguimiento; esto es la referencia.
//
// Campos por ejercicio:
//   id           identificador estable (no cambiar: enlaza tus registros guardados)
//   name         nombre visible
//   scheme       texto original "Series × Reps"
//   sets         nº de series objetivo
//   repLow/High  extremos del rango (reps o segundos)
//   unit         'reps' | 'reps_lado' | 'seg'
//   rir          texto del RIR
//   ejecucion    descripción de técnica
//   mainMuscle   músculo principal
//   secMuscles   músculos complementarios (array)
//   cues         pistas cortas para la pantalla previa (se elige una al azar)
//
// Foto del ejercicio: la app busca automáticamente "img/<id>.jpg" (o .png).

export const DUMBBELL_CAP_KG = 10;

export const DAYS = [
  {
    id: "d1", name: "Torso A", group: "torso",
    exercises: [
      { id: "d1e1", name: "Press banca con mancuernas", scheme: "3 × 8-12", sets: 3, repLow: 8, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Pectoral mayor", secMuscles: ["Tríceps", "deltoides anterior"],
        cues: ["Ahora toca pecho: no rebotes la mancuerna abajo.", "Ahora toca pecho: codos a unos 45°, no abiertos del todo.", "Ahora toca pecho: baja con control, no dejes caer el peso."],
        ejecucion: "Túmbate con los pies bien apoyados y las escápulas retraídas. Baja las mancuernas controlando hasta la altura del pecho y empuja sin bloquear los codos de golpe. Codos a unos 45° respecto al torso.",
        error: "Cuidado con abrir los codos a 90°; mantenlos a ~45° del torso para cuidar el hombro.",
        variant: { name: "Flexiones (push-up)", scheme: "3 × 8-15", sets: 3, repLow: 8, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "2 min", tempo: "2-0-1", mainMuscle: "Pectoral", secMuscles: ["Tríceps", "deltoides", "core"],
          ejecucion: "Manos algo más anchas que los hombros y cuerpo en línea recta. Baja el pecho casi al suelo con los codos a ~45° y empuja sin hundir la cadera.", error: "Cuidado con abrir del todo los codos o dejar caer la cadera; mantén el cuerpo rígido en plancha." },
      },
      { id: "d1e2", name: "Remo a una mano con mancuerna", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Dorsal ancho", secMuscles: ["Romboides", "trapecio", "bíceps", "deltoides posterior"],
        cues: ["Ahora toca espalda: tira con el codo, no con el bíceps.", "Ahora toca espalda: no gires el torso para subir más peso.", "Ahora toca espalda: aprieta arriba un instante, no tires por inercia."],
        ejecucion: "Apoya rodilla y mano del mismo lado en el banco, con la espalda neutra y casi paralela al suelo. Tira del codo hacia la cadera llevando la mancuerna al costado; aprieta la espalda arriba y baja con control.",
        error: "Cuidado con girar el tronco para subir más peso; mantén la espalda fija y tira con el codo.",
        variant: { name: "Remo con dos mancuernas inclinado", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", tempo: "2-0-1", mainMuscle: "Espalda media/dorsal", secMuscles: ["Bíceps", "deltoides posterior"],
          ejecucion: "Tronco inclinado ~45° y espalda neutra. Rema con ambas mancuernas llevando los codos hacia atrás y apretando la espalda; baja controlado.", error: "Cuidado con redondear la espalda o tirar con los bíceps; lleva los codos atrás." },
      },
      { id: "d1e3", name: "Press militar sentado con mancuernas", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Deltoides (anterior y medio)", secMuscles: ["Tríceps", "trapecio superior"],
        cues: ["Ahora toca hombro: no arquees la lumbar al empujar.", "Ahora toca hombro: baja hasta las orejas, no te quedes a medias.", "Ahora toca hombro: sube sin impulsar con las piernas."],
        ejecucion: "Sentado con la espalda apoyada y el core firme. Empuja las mancuernas desde la altura de los hombros hasta arriba sin arquear la lumbar. Baja hasta la altura de las orejas.",
        error: "Cuidado con arquear la lumbar al empujar; aprieta el core y no metas la espalda.",
        variant: { name: "Press Arnold", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2 min", tempo: "2-0-1", mainMuscle: "Deltoides", secMuscles: ["Tríceps"],
          ejecucion: "Empiezas con las palmas hacia ti a la altura del pecho; al subir rotas las muñecas hasta palmas al frente y extiendes arriba. Baja invirtiendo el giro.", error: "Cuidado con arquear la lumbar o subir con impulso; core firme." },
      },
      { id: "d1e4", name: "Aperturas en banco inclinado", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-0-1",
        mainMuscle: "Pectoral mayor (porción clavicular)", secMuscles: ["Deltoides anterior"],
        cues: ["Ahora toca pecho: es una apertura, no un press; codos fijos.", "Ahora toca pecho: no bajes tanto que fuerces el hombro.", "Ahora toca pecho: busca el estiramiento, no el peso máximo."],
        ejecucion: "Tumbado en banco inclinado con los codos ligeramente flexionados y fijos. Abre los brazos en arco hasta notar estiramiento en el pecho y cierra como si abrazaras un barril. No exageres la bajada.",
        error: "Cuidado con bajar de más o flexionar mucho el codo; arco amplio con codos casi fijos.",
        variant: { name: "Aperturas planas con mancuernas", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-0-1", mainMuscle: "Pectoral", secMuscles: ["Deltoides anterior"],
          ejecucion: "Tumbado en banco plano, codos algo flexionados y fijos. Abre en arco hasta notar estiramiento del pecho y cierra como si abrazaras un barril.", error: "Cuidado con bajar de más o doblar mucho el codo." },
      },
      { id: "d1e5", name: "Curl de bíceps", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-0-1",
        mainMuscle: "Bíceps braquial", secMuscles: ["Braquial anterior", "braquiorradial (antebrazo)"],
        cues: ["Ahora toca bíceps: sin balanceo, que no tire la espalda.", "Ahora toca bíceps: codos quietos pegados al cuerpo.", "Ahora toca bíceps: baja lento, no dejes caer la mancuerna."],
        ejecucion: "De pie, codos pegados al torso. Sube las mancuernas contrayendo el bíceps sin balancear el cuerpo. Baja lento controlando toda la fase.",
        error: "Cuidado con balancear el cuerpo para impulsar; codos pegados y solo mueve el antebrazo.",
        variant: { name: "Curl concentrado", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-0-1", mainMuscle: "Bíceps", secMuscles: ["Antebrazo"],
          ejecucion: "Sentado, con el codo apoyado en la cara interna del muslo. Sube la mancuerna contrayendo el bíceps y baja lento sin balanceo.", error: "Cuidado con despegar el codo del muslo o usar impulso." },
      },
      { id: "d1e6", name: "Extensión de tríceps sobre la cabeza", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-0-1",
        mainMuscle: "Tríceps (cabeza larga)", secMuscles: ["Resto del tríceps"],
        cues: ["Ahora toca tríceps: no abras los codos hacia los lados.", "Ahora toca tríceps: codos quietos apuntando arriba.", "Ahora toca tríceps: controla detrás de la nuca, sin tirones."],
        ejecucion: "Sujeta una mancuerna con ambas manos por encima de la cabeza. Baja flexionando solo los codos (mantenlos apuntando arriba) y extiende sin bloquear bruscamente.",
        error: "Cuidado con abrir los codos hacia los lados; mantenlos apuntando arriba y quietos.",
        variant: { name: "Patada de tríceps con mancuerna", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-0-1", mainMuscle: "Tríceps", secMuscles: ["—"],
          ejecucion: "Tronco inclinado, brazo pegado al costado y codo arriba. Extiende el antebrazo hacia atrás hasta estirar el tríceps; baja controlado.", error: "Cuidado con mover el hombro o balancear; solo se mueve el antebrazo." },
      },
    ],
  },
  {
    id: "d2", name: "Pierna A", group: "pierna",
    exercises: [
      { id: "d2e1", name: "Sentadilla goblet", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquiosurales", "core"],
        cues: ["Ahora toca cuádriceps: no metas las rodillas hacia dentro.", "Ahora toca cuádriceps: baja al menos hasta paralelo, no te quedes corto.", "Ahora toca cuádriceps: talones en el suelo, no de puntillas."],
        ejecucion: "Mancuerna pegada al pecho, pies a la anchura de los hombros. Baja sacando la cadera atrás y abriendo las rodillas, espalda recta, hasta que los muslos queden al menos paralelos. Sube empujando con los talones.",
        error: "Cuidado con dejar caer las rodillas hacia dentro; empújalas hacia fuera y talones en el suelo.",
        variant: { name: "Sentadilla con 2 mancuernas", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "2",
          descanso: "2-3 min", tempo: "2-0-1", mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquios"],
          ejecucion: "Una mancuerna en cada mano a los lados, pies a la anchura de hombros. Baja sacando la cadera atrás con la espalda recta hasta muslos paralelos y sube empujando los talones.", error: "Cuidado con que las rodillas caigan hacia dentro o redondear la espalda." },
      },
      { id: "d2e2", name: "Peso muerto rumano con mancuernas", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "3-0-1",
        mainMuscle: "Isquiosurales", secMuscles: ["Glúteo mayor", "erectores espinales (lumbar)"],
        cues: ["Ahora toca femoral: cadera atrás, no lo conviertas en sentadilla.", "Ahora toca femoral: espalda recta, no la curves al bajar.", "Ahora toca femoral: mancuernas pegadas a las piernas."],
        ejecucion: "Mancuernas frente a los muslos, rodillas algo flexionadas y fijas. Lleva la cadera hacia atrás bajando las mancuernas pegadas a las piernas hasta notar tensión en los isquios. Sube empujando la cadera adelante.",
        error: "Cuidado con redondear la espalda; columna neutra y bisagra llevando la cadera atrás.",
        variant: { name: "Buenos días con mancuerna", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", tempo: "3-0-1", mainMuscle: "Isquiosurales", secMuscles: ["Glúteos", "lumbar"],
          ejecucion: "Mancuerna sujeta al pecho, rodillas algo flexionadas. Lleva la cadera atrás bajando el tronco con la espalda recta hasta notar los isquios; sube extendiendo la cadera.", error: "Cuidado con redondear la lumbar o flexionar mucho las rodillas." },
      },
      { id: "d2e3", name: "Zancada búlgara", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquiosurales", "estabilizadores de cadera"],
        cues: ["Ahora toca pierna: baja de verdad, no te quedes corto.", "Ahora toca pierna: peso en el talón delantero, no en la punta.", "Ahora toca pierna: tronco estable, no des bandazos para equilibrarte."],
        ejecucion: "Empeine del pie trasero sobre el banco. Baja flexionando la rodilla delantera hasta unos 90°, con el tronco ligeramente inclinado. Empuja con el talón delantero para subir. Controla el equilibrio.",
        error: "Cuidado con inclinar el tronco o que la rodilla delantera se vaya hacia dentro.",
        variant: { name: "Zancada inversa con mancuernas", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
          descanso: "2-3 min", tempo: "2-0-1", mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquios"],
          ejecucion: "De pie con mancuernas a los lados. Da un paso atrás y baja la rodilla trasera hacia el suelo con el tronco erguido; empuja con la pierna delantera para volver.", error: "Cuidado con que la rodilla delantera pase la punta del pie o inclinar el tronco." },
      },
      { id: "d2e4", name: "Puente de glúteo con mancuerna", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-1-1",
        mainMuscle: "Glúteo mayor", secMuscles: ["Isquiosurales", "core"],
        cues: ["Ahora toca glúteo: aprieta arriba, no arquees la lumbar.", "Ahora toca glúteo: empuja con los talones, no con las puntas.", "Ahora toca glúteo: no apoyes del todo abajo, mantén tensión."],
        ejecucion: "Boca arriba, mancuerna sobre la cadera, pies apoyados cerca del glúteo. Eleva la cadera apretando los glúteos hasta alinear tronco y muslos. Pausa arriba y baja sin apoyar del todo.",
        error: "Cuidado con hiperextender la lumbar arriba; sube apretando glúteos, no la espalda.",
        variant: { name: "Hip thrust en banco", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-1-1", mainMuscle: "Glúteo mayor", secMuscles: ["Isquiosurales"],
          ejecucion: "Espalda alta apoyada en el banco, mancuerna sobre la cadera y pies firmes. Eleva la cadera apretando glúteos hasta alinear tronco y muslos; pausa arriba.", error: "Cuidado con hiperextender la lumbar; el empuje sale del glúteo." },
      },
      { id: "d2e5", name: "Elevación de gemelo de pie", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1",
        descanso: "1 min", tempo: "2-1-2",
        mainMuscle: "Gastrocnemio (gemelos)", secMuscles: ["Sóleo"],
        cues: ["Ahora toca gemelo: sube al máximo, no hagas medio recorrido.", "Ahora toca gemelo: pausa arriba, no rebotes.", "Ahora toca gemelo: baja lento estirando, sin caer de golpe."],
        ejecucion: "De pie (con mancuernas para más carga), eleva los talones poniéndote de puntillas al máximo. Pausa arriba 1 segundo y baja lento estirando el gemelo. En un escalón ganas rango.",
        error: "Cuidado con rebotar y usar poco rango; sube del todo y baja estirando el gemelo.",
        variant: { name: "Gemelo a una pierna en un escalón", scheme: "3 × 12-15 (lado)", sets: 3, repLow: 12, repHigh: 15, unit: "reps_lado", rir: "1",
          descanso: "1 min", tempo: "2-1-2", mainMuscle: "Gastrocnemio", secMuscles: ["Sóleo"],
          ejecucion: "Punta del pie en el borde de un escalón, sujétate para el equilibrio. Sube de puntillas al máximo, pausa, y baja estirando el gemelo por debajo del nivel del escalón.", error: "Cuidado con rebotar y usar poco rango." },
      },
      { id: "d2e6", name: "Plancha frontal", scheme: "3 × 30-45 seg", sets: 3, repLow: 30, repHigh: 45, unit: "seg", rir: "Isom.",
        descanso: "1 min", tempo: "—",
        mainMuscle: "Core (recto abdominal y transverso)", secMuscles: ["Oblicuos", "glúteos", "hombros"],
        cues: ["Ahora toca core: no dejes caer la cadera.", "Ahora toca core: no subas el culo buscando descanso.", "Ahora toca core: respira, no aguantes la respiración."],
        ejecucion: "Apóyate sobre antebrazos y puntas de los pies, con el cuerpo en línea recta de la cabeza a los talones. Aprieta abdomen y glúteos, sin hundir ni elevar la cadera. Respira con normalidad.",
        error: "Cuidado con hundir o elevar la cadera; cuerpo en línea recta de cabeza a talones.",
        variant: { name: "Dead bug", scheme: "3 × 8-10 (lado)", sets: 3, repLow: 8, repHigh: 10, unit: "reps_lado", rir: "Isom.",
          descanso: "1 min", tempo: "controlado", mainMuscle: "Core (abdomen)", secMuscles: ["—"],
          ejecucion: "Boca arriba, brazos hacia el techo y caderas/rodillas a 90°. Baja a la vez el brazo y la pierna contrarios sin despegar la lumbar del suelo; alterna lados.", error: "Cuidado con arquear la lumbar; mantenla pegada al suelo." },
      },
    ],
  },
  {
    id: "d3", name: "Torso B", group: "torso",
    exercises: [
      { id: "d3e1", name: "Press inclinado con mancuernas", scheme: "3 × 8-12", sets: 3, repLow: 8, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Pectoral superior (porción clavicular)", secMuscles: ["Deltoides anterior", "tríceps"],
        cues: ["Ahora toca pecho: no rebotes abajo ni bloquees arriba de golpe.", "Ahora toca pecho: banco a 30-45°, no demasiado vertical (eso es hombro).", "Ahora toca pecho: baja a la parte alta del pecho, controlado."],
        ejecucion: "Banco a 30-45° y escápulas retraídas. Baja las mancuernas a la parte alta del pecho y empuja hacia arriba juntándolas ligeramente. Codos a unos 45°, sin rebotar abajo.",
        error: "Cuidado con rebotar abajo o abrir los codos; baja controlado y mantén ~45°.",
        variant: { name: "Flexiones con pies elevados", scheme: "3 × 8-15", sets: 3, repLow: 8, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "2 min", tempo: "2-0-1", mainMuscle: "Pectoral superior", secMuscles: ["Deltoides", "tríceps"],
          ejecucion: "Pies sobre un banco y manos algo más anchas que los hombros. Baja el pecho controlando con los codos a ~45° y empuja manteniendo el cuerpo recto.", error: "Cuidado con hundir la cadera o abrir del todo los codos." },
      },
      { id: "d3e2", name: "Remo con apoyo de pecho", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Dorsal ancho y espalda media", secMuscles: ["Romboides", "trapecio", "deltoides posterior", "bíceps"],
        cues: ["Ahora toca espalda: pecho pegado al banco, no te despegues para hacer trampa.", "Ahora toca espalda: lleva los codos atrás, no encojas los hombros.", "Ahora toca espalda: aprieta la espalda, no tires solo con los brazos."],
        ejecucion: "Tumbado boca abajo sobre el banco inclinado, con el pecho apoyado. Deja colgar los brazos y rema llevando los codos hacia atrás, apretando la espalda. Baja con control.",
        error: "Cuidado con tirar con los bíceps en vez de la espalda; lleva los codos hacia atrás.",
        variant: { name: "Remo a una mano con mancuerna", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
          descanso: "2-3 min", tempo: "2-0-1", mainMuscle: "Espalda media/dorsal", secMuscles: ["Bíceps", "deltoides posterior"],
          ejecucion: "Rodilla y mano del mismo lado en el banco, espalda paralela al suelo. Tira del codo hacia la cadera llevando la mancuerna al costado; baja controlado.", error: "Cuidado con girar el tronco o tirar con el bíceps." },
      },
      { id: "d3e3", name: "Elevaciones laterales", scheme: "3 × 12-20", sets: 3, repLow: 12, repHigh: 20, unit: "reps", rir: "1-2",
        descanso: "1 min", tempo: "2-0-1",
        mainMuscle: "Deltoides medio", secMuscles: ["Deltoides anterior y posterior", "trapecio"],
        cues: ["Ahora toca hombro: ni impulso ni subir por encima del hombro.", "Ahora toca hombro: lidera con los codos, no con las manos.", "Ahora toca hombro: poco peso bien hecho, no cargues de más."],
        ejecucion: "De pie, con una leve flexión de codo. Eleva las mancuernas hacia los lados hasta la altura de los hombros, liderando con los codos. Sube sin impulso y baja lento; no pases del hombro.",
        error: "Cuidado con usar impulso y pasar del hombro; sube controlado hasta la altura del hombro.",
        variant: { name: "Elevación lateral con banda", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1-2",
          descanso: "1 min", tempo: "2-0-1", mainMuscle: "Deltoides medio", secMuscles: ["—"],
          ejecucion: "De pie sobre la banda, sujeta los extremos. Eleva los brazos a los lados hasta la altura del hombro liderando con los codos; baja lento.", error: "Cuidado con usar impulso o subir por encima del hombro." },
      },
      { id: "d3e4", name: "Pullover con mancuerna", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-1-1",
        mainMuscle: "Dorsal ancho", secMuscles: ["Pectoral", "tríceps (cabeza larga)", "serrato anterior"],
        cues: ["Ahora toca espalda: codos casi fijos, no flexiones para 'ayudarte'.", "Ahora toca espalda: rango cómodo detrás, no fuerces el hombro.", "Ahora toca espalda: controla la bajada, no dejes caer el peso."],
        ejecucion: "Tumbado en el banco, sujeta una mancuerna con ambas manos sobre el pecho. Llévala en arco por detrás de la cabeza con los codos casi rectos hasta notar estiramiento, y regresa contrayendo pecho y dorsal.",
        error: "Cuidado con doblar mucho los codos o arquear la lumbar; brazos casi rectos, costillas abajo.",
        variant: { name: "Pullover en suelo", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-1-1", mainMuscle: "Dorsal y pectoral", secMuscles: ["Tríceps"],
          ejecucion: "Tumbado en el suelo, mancuerna con ambas manos sobre el pecho. Llévala en arco tras la cabeza con los codos casi rectos hasta estirar, y vuelve. El suelo limita el rango.", error: "Cuidado con doblar mucho los codos o arquear la lumbar." },
      },
      { id: "d3e5", name: "Curl martillo", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-0-1",
        mainMuscle: "Braquial y braquiorradial", secMuscles: ["Bíceps braquial"],
        cues: ["Ahora toca brazo: agarre neutro, palmas enfrentadas todo el rato.", "Ahora toca brazo: sin balanceo, codos quietos.", "Ahora toca brazo: baja controlando, no sueltes de golpe."],
        ejecucion: "Como el curl, pero con agarre neutro (palmas enfrentadas), pulgares hacia arriba. Sube sin balanceo y baja controlado. Trabaja el braquial y el antebrazo.",
        error: "Cuidado con balancear el cuerpo; agarre neutro, codos quietos y bajada controlada.",
        variant: { name: "Curl de bíceps alterno", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-0-1", mainMuscle: "Bíceps", secMuscles: ["Antebrazo"],
          ejecucion: "De pie, sube alternando cada mancuerna rotando la palma hacia arriba al subir; codos pegados al torso y sin balanceo.", error: "Cuidado con balancear el cuerpo para impulsar." },
      },
      { id: "d3e6", name: "Press cerrado en suelo", scheme: "2 × 12-15", sets: 2, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1-2 min", tempo: "2-0-1",
        mainMuscle: "Tríceps", secMuscles: ["Pectoral", "deltoides anterior"],
        cues: ["Ahora toca tríceps: codos pegados al cuerpo, no abiertos.", "Ahora toca tríceps: el suelo marca el rango, no rebotes los codos.", "Ahora toca tríceps: empuja pensando en el tríceps, no en el pecho."],
        ejecucion: "Tumbado en el suelo, mancuernas con agarre neutro y codos pegados al cuerpo. Empuja hacia arriba enfocando el tríceps. El suelo limita el rango y protege los hombros.",
        error: "Cuidado con abrir los codos; mantenlos pegados al cuerpo para enfocar el tríceps.",
        variant: { name: "Fondos en banco (bench dips)", scheme: "2 × 10-15", sets: 2, repLow: 10, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1-2 min", tempo: "2-0-1", mainMuscle: "Tríceps", secMuscles: ["Pecho", "hombro"],
          ejecucion: "Manos en el borde del banco y piernas al frente. Baja flexionando los codos pegados al cuerpo hasta ~90° y empuja con el tríceps para subir.", error: "Cuidado con abrir los codos o bajar de más (estrés en el hombro)." },
      },
    ],
  },
  {
    id: "d4", name: "Pierna B", group: "pierna",
    exercises: [
      { id: "d4e1", name: "Zancada inversa con mancuernas", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Cuádriceps y glúteo mayor", secMuscles: ["Isquiosurales", "estabilizadores"],
        cues: ["Ahora toca pierna: paso atrás firme, no pierdas el equilibrio.", "Ahora toca pierna: tronco erguido, no te vayas hacia delante.", "Ahora toca pierna: baja la rodilla de atrás, no te quedes corto."],
        ejecucion: "De pie con mancuernas a los lados. Da un paso atrás y baja la rodilla trasera hacia el suelo manteniendo el tronco erguido. Empuja con la pierna delantera para volver.",
        error: "Cuidado con que la rodilla delantera pase la punta del pie; mantén el tronco erguido.",
        variant: { name: "Zancada hacia delante con mancuernas", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
          descanso: "2-3 min", tempo: "2-0-1", mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquios"],
          ejecucion: "Paso al frente bajando la cadera hasta que la rodilla trasera casi toca el suelo; empuja con el talón delantero para volver.", error: "Cuidado con que la rodilla delantera pase la punta del pie." },
      },
      { id: "d4e2", name: "Peso muerto rumano a una pierna", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
        descanso: "2-3 min", tempo: "3-0-1",
        mainMuscle: "Isquiosurales y glúteo", secMuscles: ["Erectores espinales", "estabilizadores de cadera y tobillo"],
        cues: ["Ahora toca femoral: cadera atrás, no curves la espalda.", "Ahora toca femoral: ve despacio, el equilibrio es parte del ejercicio.", "Ahora toca femoral: no hagas sentadilla, es bisagra de cadera."],
        ejecucion: "Sobre una pierna, mancuerna(s) al frente. Lleva la cadera hacia atrás bajando el tronco mientras la pierna libre se extiende hacia atrás. Espalda recta y subida controlada. Es un buen reto de equilibrio.",
        error: "Cuidado con que la cadera se abra de lado; mantén las caderas niveladas y la espalda recta.",
        variant: { name: "PM rumano a dos piernas con mancuernas", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", tempo: "3-0-1", mainMuscle: "Isquiosurales", secMuscles: ["Glúteos", "lumbar"],
          ejecucion: "Mancuernas frente a los muslos, rodillas algo flexionadas. Cadera atrás bajando con la espalda recta hasta notar los isquios; sube extendiendo la cadera.", error: "Cuidado con redondear la espalda." },
      },
      { id: "d4e3", name: "Sentadilla goblet con tempo", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
        descanso: "2-3 min", tempo: "3-1-1",
        mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquiosurales", "core"],
        cues: ["Ahora toca cuádriceps: baja en 3-4 s, no aceleres la bajada.", "Ahora toca cuádriceps: rodillas hacia fuera, no hacia dentro.", "Ahora toca cuádriceps: el peso es lo de menos, manda el tempo."],
        ejecucion: "Igual que la goblet, pero baja en 3-4 segundos controlando cada centímetro y sube a velocidad normal. El tempo lento aumenta el estímulo con poco peso.",
        error: "Cuidado con acelerar la bajada; controla los 3-4 segundos de descenso.",
        variant: { name: "Sentadilla con 2 mancuernas (tempo)", scheme: "3 × 10-12", sets: 3, repLow: 10, repHigh: 12, unit: "reps", rir: "2",
          descanso: "2-3 min", tempo: "3-1-1", mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquios"],
          ejecucion: "Una mancuerna en cada mano; baja en 3-4 segundos controlando, pausa breve abajo y sube a velocidad normal.", error: "Cuidado con acelerar la bajada." },
      },
      { id: "d4e4", name: "Step-up al banco", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "1-2",
        descanso: "2-3 min", tempo: "2-0-1",
        mainMuscle: "Cuádriceps y glúteo mayor", secMuscles: ["Isquiosurales", "gemelos", "estabilizadores"],
        cues: ["Ahora toca pierna: sube con el pie de arriba, no te impulses con el de abajo.", "Ahora toca pierna: pie completo en el banco, no de puntillas.", "Ahora toca pierna: baja controlando, no te dejes caer."],
        ejecucion: "Coloca un pie completo sobre el banco. Sube empujando con ese talón hasta extender la pierna, sin impulsarte con la pierna de abajo. Baja controlado. Mancuernas a los lados para añadir carga.",
        error: "Cuidado con impulsarte con la pierna de abajo; sube empujando solo con la pierna de arriba.",
        variant: { name: "Zancada búlgara", scheme: "3 × 10-12 (lado)", sets: 3, repLow: 10, repHigh: 12, unit: "reps_lado", rir: "2",
          descanso: "2-3 min", tempo: "2-0-1", mainMuscle: "Cuádriceps", secMuscles: ["Glúteos", "isquios"],
          ejecucion: "Empeine del pie trasero en el banco; baja la rodilla delantera a ~90° con el tronco algo inclinado y empuja con el talón delantero.", error: "Cuidado con inclinar demasiado el tronco o que la rodilla caiga hacia dentro." },
      },
      { id: "d4e5", name: "Elevación de gemelo sentado", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1",
        descanso: "1 min", tempo: "2-1-2",
        mainMuscle: "Sóleo", secMuscles: ["Gastrocnemio (gemelos)"],
        cues: ["Ahora toca gemelo: rango completo, no medio movimiento.", "Ahora toca gemelo: pausa arriba, sin rebotes.", "Ahora toca gemelo: baja lento estirando bien."],
        ejecucion: "Sentado, con las mancuernas apoyadas sobre las rodillas. Eleva los talones poniéndote de puntillas, pausa arriba y baja lento. Enfatiza el sóleo.",
        error: "Cuidado con poco rango y rebote; pausa arriba y estira abajo.",
        variant: { name: "Gemelo de pie con mancuernas", scheme: "3 × 15-20", sets: 3, repLow: 15, repHigh: 20, unit: "reps", rir: "1",
          descanso: "1 min", tempo: "2-1-2", mainMuscle: "Gastrocnemio", secMuscles: ["Sóleo"],
          ejecucion: "De pie con mancuernas para añadir carga, sube de puntillas al máximo, pausa arriba y baja estirando el gemelo.", error: "Cuidado con rebotar y usar poco rango." },
      },
      { id: "d4e6", name: "Elevación de piernas tumbado", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
        descanso: "1 min", tempo: "2-0-2",
        mainMuscle: "Recto abdominal (parte inferior)", secMuscles: ["Flexores de cadera", "oblicuos"],
        cues: ["Ahora toca abdomen: no despegues la lumbar de golpe.", "Ahora toca abdomen: baja controlando, no dejes caer las piernas.", "Ahora toca abdomen: si tiras de cuello o cadera, reduce el rango."],
        ejecucion: "Boca arriba, manos bajo los glúteos. Sube las piernas casi rectas controlando, sin despegar la lumbar de golpe, y baja lento sin tocar el suelo.",
        error: "Cuidado con despegar la lumbar y arquear; mantén la zona baja pegada al suelo.",
        variant: { name: "Crunch inverso", scheme: "3 × 12-15", sets: 3, repLow: 12, repHigh: 15, unit: "reps", rir: "1-2",
          descanso: "1 min", tempo: "2-0-2", mainMuscle: "Recto abdominal (inferior)", secMuscles: ["Flexores de cadera"],
          ejecucion: "Boca arriba, lleva las rodillas hacia el pecho elevando la pelvis del suelo con control; baja sin arquear la lumbar.", error: "Cuidado con usar impulso o arquear la lumbar." },
      },
    ],
  },
];

export const PRINCIPLES = [
  { title: "Frecuencia y reparto", body: "4 sesiones (p. ej. Lun · Mar · Jue · Vie), cada grupo muscular entrenado 2 veces por semana. Calienta 5 min antes de cada sesión." },
  { title: "Sobrecarga progresiva (doble progresión)", body: "Empieza en el extremo bajo del rango con buena técnica. Cuando alcances el extremo alto en todas las series, sube peso. Al llegar a tu tope de 10 kg, progresa con más repeticiones, fase excéntrica más lenta (3-4 s) o versiones a una pierna/un brazo." },
  { title: "Esfuerzo (RIR)", body: "El RIR son las repeticiones que dejas 'en la recámara'. RIR 2 = podrías hacer 2 más con buena forma. Prioriza la técnica antes que llegar al fallo." },
  { title: "Suplementación y recuperación", body: "Proteína 1,6-2,2 g por kg de peso al día. Creatina 3-5 g diarios constantes (la hora es indiferente). Dormir bien es donde se construye el músculo." },
  { title: "Tempo", body: "Velocidad de cada fase de la repetición en segundos (excéntrica-pausa-concéntrica). Ej.: 3-1-1 = bajar en 3 s, pausa de 1 s, subir en 1 s. Alargar la bajada sube el estímulo sin tocar el peso: una de tus palancas al toparte con los 10 kg." },
  { title: "Variante (↳)", body: "Bajo cada ejercicio tienes una alternativa casera con sus mismos datos, por si te falla el banco, quieres variar el estímulo o algo te molesta." },
  { title: "Nota", body: "Plan orientativo. Ajusta cargas y volumen según tu recuperación. Ante dolor (no la molestia muscular normal), detente y revisa la técnica. Los enlaces abren una búsqueda en YouTube con buenas demostraciones del ejercicio." },
];

export const EXERCISE_MEDIA = {
  d1e1: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/1.jpg"], en: "Dumbbell Bench Press", source: "Free Exercise DB", ok: true },
  d1e2: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/One-Arm_Dumbbell_Row/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/One-Arm_Dumbbell_Row/1.jpg"], en: "One-Arm Dumbbell Row", source: "Free Exercise DB", ok: false },
  d1e3: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Shoulder_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Shoulder_Press/1.jpg"], en: "Dumbbell Shoulder Press", source: "Free Exercise DB", ok: true },
  d1e4: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Flyes/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Flyes/1.jpg"], en: "Incline Dumbbell Flyes", source: "Free Exercise DB", ok: false },
  d1e5: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bicep_Curl/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bicep_Curl/1.jpg"], en: "Dumbbell Bicep Curl", source: "Free Exercise DB", ok: true },
  d1e6: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Dumbbell_Triceps_Extension/1.jpg"], en: "Standing Dumbbell Triceps Extension", source: "Free Exercise DB", ok: false },
  d2e1: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/1.jpg"], en: "Dumbbell Squat", source: "Free Exercise DB", ok: true },
  d2e2: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Stiff-Legged_Dumbbell_Deadlift/1.jpg"], en: "Stiff-Legged Dumbbell Deadlift", source: "Free Exercise DB", ok: false },
  d2e3: { urls: ["https://fitnessprogramer.com/wp-content/uploads/2021/05/Dumbbell-Bulgarian-Split-Squat.gif"], en: "", source: "fitnessprogramer.com", ok: false },
  d2e4: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Butt_Lift_Bridge/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Butt_Lift_Bridge/1.jpg"], en: "Butt Lift (Bridge)", source: "Free Exercise DB", ok: true },
  d2e5: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Calf_Raise_On_A_Dumbbell/1.jpg"], en: "Calf Raise On A Dumbbell", source: "Free Exercise DB", ok: true },
  d2e6: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/1.jpg"], en: "Plank", source: "Free Exercise DB", ok: false },
  d3e1: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Incline_Dumbbell_Press/1.jpg"], en: "Incline Dumbbell Press", source: "Free Exercise DB", ok: false },
  d3e2: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Incline_Row/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Incline_Row/1.jpg"], en: "Dumbbell Incline Row", source: "Free Exercise DB", ok: true },
  d3e3: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Side_Lateral_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Side_Lateral_Raise/1.jpg"], en: "Side Lateral Raise", source: "Free Exercise DB", ok: false },
  d3e4: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent-Arm_Dumbbell_Pullover/1.jpg"], en: "Bent-Arm Dumbbell Pullover", source: "Free Exercise DB", ok: true },
  d3e5: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Alternate_Hammer_Curl/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Alternate_Hammer_Curl/1.jpg"], en: "Alternate Hammer Curl", source: "Free Exercise DB", ok: true },
  d3e6: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Floor_Press/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Floor_Press/1.jpg"], en: "Dumbbell Floor Press", source: "Free Exercise DB", ok: true },
  d4e1: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Rear_Lunge/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Rear_Lunge/1.jpg"], en: "Dumbbell Rear Lunge", source: "Free Exercise DB", ok: true },
  d4e2: { urls: ["https://fitnessprogramer.com/wp-content/uploads/2022/09/Dumbbell-Single-Leg-Deadlift.gif"], en: "", source: "fitnessprogramer.com", ok: false },
  d4e3: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Squat/1.jpg"], en: "Dumbbell Squat", source: "Free Exercise DB", ok: true },
  d4e4: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Step_Ups/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Step_Ups/1.jpg"], en: "Dumbbell Step Ups", source: "Free Exercise DB", ok: true },
  d4e5: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Seated_One-Leg_Calf_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Seated_One-Leg_Calf_Raise/1.jpg"], en: "Dumbbell Seated One-Leg Calf Raise", source: "Free Exercise DB", ok: true },
  d4e6: { urls: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg", "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Flat_Bench_Lying_Leg_Raise/1.jpg"], en: "Flat Bench Lying Leg Raise", source: "Free Exercise DB", ok: false },
};

export function exerciseImages(exId) {
  const m = EXERCISE_MEDIA[exId];
  return (m && m.urls) ? m.urls : [];
}

export function exerciseSource(exId) {
  const m = EXERCISE_MEDIA[exId];
  return (m && m.source) ? m.source : "";
}

export const EXERCISE_INDEX = (() => {
  const idx = {};
  for (const day of DAYS) for (const ex of day.exercises) idx[ex.id] = { ...ex, dayId: day.id, dayName: day.name };
  return idx;
})();

export function videoUrl(name) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(name + " técnica mancuernas");
}
